spring.application.name=health-care
server.address=0.0.0.0
server.port=8081

gemini.api.key=AIzaSyBLpBu8b9Du9rlR2puFQ0R9hd4ACg27Zuc

spring.datasource.url=jdbc:mysql://localhost:3306/healthcare?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Faijan78678600

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=faijkhaaan00786@gmail.com
spring.mail.password=oqhrvrrfeusibomm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Frontend URL ? doctor email mein join link ke liye
# Apna index.html jahan se khulta hai woh URL daalo
app.frontend.url=http://localhost:8081

#Step 1: CMD mein run karo (project folder mein):
# keytool -genkeypair -alias maatricare -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore src/main/resources/maatricare.p12 -validity 3650 -storepass maatri123

# File upload directory
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
